### PR TITLE
Feature/datetime

### PR DESCRIPTION
**Pull request by crisward**
Got the read and writing of date/time working.

If I've missed anything, let me know.

### CODE REVIEW

**Comment by crisward** [comment]
Think the failing test may be due to the mysql version, I think the microsecond support maybe recent. It's passing locally.

**Comment by bcardiff** [comment]
Hey @crisward , why this PR was closed?

**Comment by crisward** [comment]
I've included it in the text field PR. I wanted to test them together, I also fixed the failing test (see open PR)

**Comment by bcardiff** [comment]
Oh, It would be better to do it in separate I think. If you were able to fix the failing test I was going to ask for a [squash everything](https://github.com/crystal-lang/crystal/blob/master/Contributing.md#maintain-clean-pull-requests) here in a single commit so I can merge it. I will do some comments in the text/blob PR.

MySql/DateTime-Crystal/Time is less related to text/blob than MySql/Time-Crystal/Time::Span.
So actually we can go on and on adding conversions, but let's do it one at a time.

If it's too much bother, I can pick it up from here and get your changes for DateTime support. As you prefer. I am glad for your contributions and I don't to push them back.

**Comment by asterite** [comment]
@bcardiff When you decide to merge a pull request you can choose to squash the commits, so there's no need to ask this anymore :-)

**Comment by bcardiff** [comment]
I forgot about that :-) even so, we need the fix for the test. So @crisward if you can bring that change here I should be able to squash it.

**Comment by crisward** [comment]
ok will do

**Pull request merged**
