### PR TITLE
added tinyint and smallint as int8 and int16

### LINKED ISSUE #12: support  TINYINT(1)
I think that's what generates this anyway:

not supported (Exception)
[4387954258] *CallStack::unwind:Array(Pointer(Void)) +82
[4387954161] *CallStack#initialize:Array(Pointer(Void)) +17
[4387954120] *CallStack::new:CallStack +40
[4387860777] *raise:NoReturn +25
[4387860737] *raise:NoReturn +17
[4389068958] *MySql::Type+@MySql::Type::read:NoReturn +30
[4389072710] *MySql::ResultSet#read:(Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil) +1238

(the current error message doesn't say "what" isn't supported, as it were).

### PR DESCRIPTION
**Pull request by crisward**
Hopefully fixes #12

### CODE REVIEW

**Comment by crisward** [comment]
I've noticed with both these Int8, Int16 and Time types, they needed to be added here too, 
https://github.com/crystal-lang/crystal-db/blob/master/src/db.cr#L72

otherwise I get the following errror

```
in src/app/pages/page-repository.cr:105: instantiating 'DB::Database#exec(String, (String | Nil), (Int32 | Nil), (String | Nil), (String | Nil), (String | Nil), (Int8 | Nil), (Int8 | Nil), (Int32 | Nil), (String | Nil), String, String, Int32)'

      res = @db.exec("
                ^~~~
```

I'm using db v.0.2.0

**Comment by crisward** [comment]
The failing tests seem to have nothing to do with the code pushed. 
Any idea when travis will be fixed and if this change will be merged. Working from by own fork at the moment but it's not ideal.

**Comment by bcardiff** [comment]
squashed/merged at a1db0df999cd6247b946745893ed98979cc113a9.
I added some missing specs for covering the params binding of the [last commit](https://github.com/crystal-lang/crystal-mysql/pull/15/commits/69cc5b6c18e3e4a838547abff45d01d8a6e7da6b)

```diff
diff --git a/spec/driver_spec.cr b/spec/driver_spec.cr
index 36a7a9b..24164b7 100644
--- a/spec/driver_spec.cr
+++ b/spec/driver_spec.cr
@@ -96,7 +96,7 @@ describe Driver do
     end
   end
 
-  {% for value in [1, 1_i64, "hello", 1.5, 1.5_f32] %}
+  {% for value in [54_i16, 1_i8, 5_i8, 1, 1_i64, "hello", 1.5, 1.5_f32] %}
     it "executes and select nil as type of {{value.id}}" do
       with_db do |db|
         db.scalar("select null").should be_nil
```

Thanks!

**Comment by crisward** [comment]
Cool, many thanks.

**Pull request closed without merging**
