### PR TITLE
fix for https://github.com/crystal-lang/crystal-mysql/issues/22

### PR DESCRIPTION
**Pull request by crisward**
Needed this to get my tests to pass, using my fork for now. Feel free to merge if you can confirm. Or discard if the issue has another cause.

Many thanks.

### CODE REVIEW

**Comment by bcardiff** [comment]
@crisward I was still not able to need this patch in my side. Is there any new information to bring to the table or has vanished from your side the issue?

**Comment by benoist** [comment]
I can reproduce this with the following

```crystal
require "mysql"
require "db"

class Record
  @@connection : DB::Database = DB.open "mysql://root@localhost/appmonit_db_development"
end
```

**Comment by crisward** [comment]
I'm also creating my connection as @@db =

**Comment by benoist** [comment]
If i change the code to 

```crystal

  def initialize(@io : IO, @connection : Connection)
    begin
      header = uninitialized UInt8[4]
      io.read_fully(header.to_slice)
    rescue IO::EOFError
      raise DB::ConnectionLost.new(@connection)
    end
    @length = @remaining = header[0].to_i + (header[1].to_i << 8) + (header[2].to_i << 16)
    @seq = header[3]
  end

```
the error is gone.

**Comment by crisward** [comment]
Thanks.

**Pull request merged**
