### PR TITLE
Update to crystal 0.28.0

### PR DESCRIPTION
**Pull request by bcardiff**
Ref: https://github.com/crystal-lang/crystal/pull/5346

### CODE REVIEW

**Comment by straight-shoota** [comment]
I guess we should better have `Time.new` as an alias at least for 0.28.0 and decide whether we want to keep it or replace it with a deprecation message for 0.29.0. This would be easier for shards like this, which could simply switch from `Time.new` to `Time.local` *after* `0.28.0` has been released.

**Comment by bcardiff** [comment]
I'm all in to have an alias here for one version. The checks will still be there probably, I like to not force the user to migrate to the latest as soon it comes out.

But I would be able to add it after `0.28.0` release, not needing to do the `0.28.0-0` to match `0.28.0-dev`.

**Comment by straight-shoota** [comment]
Agreed.

But I'd put this change on hold. There is a chance we decide to keep `Time.now` as an alias indefinitely. Then this wouldn't be necessary anyway.

**Comment by bcardiff** [comment]
@straight-shoota I think this can be merged now. I've updated the version check now that 0.28.0 is out and added a couple of `//`.

crystal-db requires Crytal 0.25, in the near future I will bump that in another release to require 0.27 and the macro-ifs will be able to go away.

**Pull request merged**
